name: Build and Deploy Flutter Web to Firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Spécifiez la version de Flutter ici

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      - name: Clean coverage report
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: proximity_client/coverage/lcov.cleaned.info

      - name: Build Flutter web app
        run: |
          cd proximity_client
          flutter build web

      - name: Install Firebase CLI locally
        run: |
          npm install --save-dev firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd proximity_client
          npx firebase-tools deploy --only hosting --token "$FIREBASE_TOKEN"
