# Define a workflow to generate coverage report and upload to codecov
name: Coverage And Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Installation
  installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Get Flutter dependencies
        run: |
          cd proximity_client
          flutter pub get

      - name: Install lcov
        run: sudo apt-get install -y lcov

  # Job 2: Run Tests
  run_tests:
    runs-on: ubuntu-latest
    needs: installation

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Get Flutter dependencies
        run: |
          cd proximity_client
          flutter pub get

      - name: Run tests and generate coverage report
        run: |
          cd proximity_client
          flutter test --coverage test/

  # Job 3: Clean Coverage Report
  clean_coverage:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Get Flutter dependencies
        run: |
          cd proximity_client
          flutter pub get

      - name: Clean coverage report
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info

  # Job 4: Upload Coverage Report
  upload_coverage:
    runs-on: ubuntu-latest
    needs: clean_coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Get Flutter dependencies
        run: |
          cd proximity_client
          flutter pub get

      # - name: Upload coverage report to codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
