# Define a workflow to generate coverage report and upload to codecov
name: Coverage And Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Perl
      - name: Install Perl
        if: runner.os == 'Windows'
        run: |
          # Télécharger l'installateur Perl
          Invoke-WebRequest -Uri "https://strawberryperl.com/download/5.34.0.1/strawberry-perl-5.34.0.1-64bit.msi" -OutFile "perl_installer.msi"

          # Installer Perl
          Start-Process -Wait msiexec.exe -ArgumentList '/i', 'perl_installer.msi', '/quiet'

          # Créer une association pour Perl
          assoc .perl=Perl.File
          ftype Perl.File=C:\Strawberry\perl\bin\perl.exe "%1" %*

      # Install lcov
      - name: Install lcov
        if: runner.os == 'Windows'
        run: |
          # Télécharger l'exécutable lcov pour Windows
          Invoke-WebRequest -Uri "https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15-win64.zip" -OutFile "lcov.zip"

          # Extraire l'exécutable lcov
          Expand-Archive -Path "lcov.zip" -DestinationPath "lcov"

          # Ajouter le répertoire lcov à la variable PATH
          $env:PATH += ";$(pwd)/lcov"

          # Vérifier l'installation de lcov
          lcov --version

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Changer de répertoire vers proximity_client
          flutter test --coverage test/

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
        
      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info
