name: Coverage And Test (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Stage: Test
  coverage_flutter_test:
    name: Run Flutter Tests and Generate Coverage
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Specify your Flutter version here

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install lcov
        run: brew install lcov

      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info --ignore-errors unused

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info

  # Stage: Analyze
  analyze_flutter_code:
    name: Analyze Flutter Code
    runs-on: macos-latest
    needs: coverage_flutter_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: |
          cd proximity_client
          flutter analyze

  # Stage: Build
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    needs: [coverage_flutter_test, analyze_flutter_code]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build iOS app
        run: | 
          cd proximity_client
          flutter build ios -t lib/main.dart
