# Define a workflow to generate coverage report and upload to codecov
name: Coverage And Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage_and_sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Specify your Flutter version here

      # Install lcov
      - name: Install lcov
        run: sudo apt-get install -y lcov

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info

      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./proximity_client/coverage/lcov.cleaned.info


    # Analyze code with SonarCloud
      - name: Analyze code with SonarCloud
        run: |
          sudo apt-get install -y default-jre
          sudo apt-get install -y unzip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip sonar-scanner-cli-4.6.0.2311-linux.zip
          export PATH=$PATH:/home/buzz/Documents/sonnar/sonar-scanner-4.6.0.2311-linux/bin
          sonar-scanner \
            -Dsonar.projectKey=buzz30gotcho \
            -Dsonar.organization=buzz30gotcho \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{secrets.SONARCLOUD_TOKEN}}
