name: Analysis (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud_analysis:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Install Flutter Windows
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Specify your Flutter version here

      # Mis a jour de Flutter
      - name: Updates Flutter
        run: flutter pub get 

      # Install lcov for Windows
      - name: Install lcov
        run: |
          Invoke-WebRequest -Uri "https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz" -OutFile "lcov-1.15.tar.gz"
          tar -xzvf lcov-1.15.tar.gz
          cd lcov-1.15
          make install 

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      # Clean coverage report (if needed)
      - name: Clean coverage report
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
