name: Coverage And Test (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Stage: Test
  coverage_flutter_test:
    name: Run Flutter Tests and Generate Coverage
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Specify your Flutter version here

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install lcov
        run: brew install lcov

      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info --ignore-errors unused

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info


  # Job 5: Build Android APK
  build_ios:
    name: Build Flutter (ios)
    needs: [coverage_flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios


