# Define a workflow to generate coverage report and upload to codecov
name: Coverage And Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Perl
      - name: Install Perl
        run: |
          # Download Perl installer
          Invoke-WebRequest -Uri "https://strawberryperl.com/download/5.34.0.1/strawberry-perl-5.34.0.1-64bit.msi" -OutFile "perl-installer.msi"

          # Install Perl silently
          Start-Process msiexec.exe -ArgumentList "/i", "perl-installer.msi", "/qn" -NoNewWindow -Wait

          # Add Perl to PATH
          $env:PATH += ";C:\Strawberry\perl\bin"

      # Define correct path of GCOV executable in geninfo.perl
      - name: Define GCOV path in geninfo.perl
        run: |
          $gcov_tool = "C:\\Program Files\\GCOV\\gcov.exe";
          (Get-Content -Path "geninfo.perl") -replace 'our \$gcov_tool = "C:\\Program Files\\GCOV\\gcov.exe";', '$gcov_tool = "C:\\Strawberry\\c\\bin\\gcov.exe"' | Set-Content -Path "geninfo.perl"

      # Define correct path of Perl executable in lcov.bat
      - name: Define Perl path in lcov.bat
        run: |
          (Get-Content -Path "lcov.bat") -replace 'set perl=C:\\CORRECT_PATH_TO\\Perl.exe', 'set perl=C:\\Strawberry\\perl\\bin\\perl.exe' | Set-Content -Path "lcov.bat"

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage  test/

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
        
      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info
