name: SonarCloud Analysis (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud_analysis:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Install Flutter Windows
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Specify your Flutter version here
          
      # Install SonarScanner
      - name: Install SonarScanner
        if: runner.os == 'Windows'
        run: |
          # Télécharger le scanner Sonar
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-windows.zip" -OutFile "sonar-scanner.zip"

          # Décompresser le scanner Sonar
          Expand-Archive -Path sonar-scanner.zip -DestinationPath sonar-scanner

          # Définir le chemin de destination
          $destinationPath = "C:\sonar-scanner"

          # Créer le dossier s'il n'existe pas
          if (!(Test-Path $destinationPath)) {
              mkdir $destinationPath
          }

          # Copier le scanner Sonar vers l'emplacement désiré sur l'environnement Windows
          Copy-Item -Path "sonar-scanner\*" -Destination $destinationPath -Recurse

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      # Clean coverage report (if needed)
      # Note: SonarCloud typically analyzes code without needing to clean coverage reports
      # - name: Clean coverage report
      #   run: |
      #     cd proximity_client
      #     lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info

      # Analyze code with SonarCloud
      - name: Analyze code with SonarCloud
        run: |
          sonar-scanner \
            -Dsonar.projectKey=<buzz30gotcho> \
            -Dsonar.organization=<buzz30gotcho> \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}

      # Note: Replace <Your_Project_Key>, <Your_Organization_Key> and ${{ secrets.SONARCLOUD_TOKEN }} with actual values
