# Define a workflow to generate coverage report and upload to codecov
name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          flutter test --coverage

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info

      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ CODECOV_TOKEN.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info
