# Define a workflow to generate coverage report and upload to codecov
name: Coverage And Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Chocolatey
      - name: Install Chocolatey
        if: runner.os == 'Windows'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      # Install Strawberry Perl via Chocolatey
      - name: Install Strawberry Perl
        if: runner.os == 'Windows'
        run: choco install strawberryperl --yes

      # Verify Strawberry Perl installation
      - name: Verify Perl installation
        if: runner.os == 'Windows'
        run: perl --version

      # Install lcov (for Windows)
      - name: Install lcov
        if: runner.os == 'Windows'
        run: |
          # Télécharger l'exécutable lcov pré-compilé pour Windows depuis une source fiable
          Invoke-WebRequest -Uri "https://downloads.sourceforge.net/project/ltp/lcov/lcov-1.14/lcov-1.14-1.noarch.rpm" -OutFile "lcov.exe"
      
          # Vérifier l'installation de lcov
          .\lcov.exe --version

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage  test/

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
        
      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info
