name: Coverage And Test (Linux and macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.0'  # Updated Flutter version

      - name: Update Flutter
        run: flutter pub get

      # Install lcov (for Linux and macOS)
      - name: Install lcov
        run: sudo apt-get install -y lcov

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          flutter test --coverage

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
          ls -la coverage # List files in the coverage
          
      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info

  macOS:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.0'  # Updated Flutter version

      - name: Update Flutter
        run: flutter pub get

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          flutter test --coverage

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
          ls -la coverage # List files in the coverage
          
      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info
