# Define a workflow to generate coverage report and upload to codecov
name: Coverage And Test (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Perl
      - name: Install Perl
        if: runner.os == 'Windows'
        run: |
          # Download Perl installer
          Invoke-WebRequest -Uri "https://strawberryperl.com/" -OutFile "perl_installer"

          # Install Perl
          Start-Process -Wait msiexec.exe -ArgumentList '/i', 'perl_installer.msi', '/quiet'

          # Create association for Perl
          assoc .perl=Perl.File
          ftype Perl.File=C:\Strawberry\perl\bin\perl.exe "%1" %*

      # Install lcov
      - name: Install lcov
        if: runner.os == 'Windows'
        run: |
          # Define correct path of GCOV executable in geninfo.perl
          # (You may need to edit geninfo.perl manually)
          # Example: $gcov_tool = "C:\\Program Files\\MinGW\\bin\\gcov.exe";

          # Define correct path of Perl executable in lcov.bat
          # (You may need to edit lcov.bat manually)
          # Example: set perl=C:\Strawberry\perl\bin\perl.exe

          # Download lcov executable (you may need to replace the URL with a valid one)
          Invoke-WebRequest -Uri "https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15-win64.zip" -OutFile "lcov.zip"

          # Extract lcov executable
          Expand-Archive -Path "lcov.zip" -DestinationPath "lcov"

          # Add lcov directory to PATH
          $env:PATH += ";$(pwd)/lcov"

          # Check lcov installation
          lcov --version

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          cd proximity_client  # Change directory to proximity_client
          flutter test --coverage test/

      # Clean coverage report
      - name: Clean coverage report  
        run: |
          cd proximity_client
          lcov --remove coverage/lcov.info '*/test/*' -o coverage/lcov.cleaned.info
        
      # Upload coverage report to codecov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.cleaned.info
